### ISSUE TITLE
BUG:  Copy/Open with Strongbox Broken

### ISSUE THREAD

**Issue by shad0whawk** [mmcguill/Strongbox#118]
The Copy To / Open With functionality within Strongbox seems to no longer work correctly in the latest version (1.28.0).  I've tried two different phones running iOS 12.2 and neither will do it anymore.  Previously, I would use another app--in my case Synqion--and select "Open in..." followed by Strongbox, and the database would be copied to Strongbox at which time it prompts me to either update or add as new if it already exists.  The new behavior after selecting "Open in..." followed by Strongbox only opens the Strongbox app but does not copy in or load the database I chose to copy.  If I force-close the app, I get a message that states, "Error Opening - could not access this file" after doing this.  If I don't force-close the app, nothing occurs after doing this.  I also tried it with OneDrive and got the same result. 

I've tried it with the application lock enabled and disabled and no change.  Initially I thought maybe that was hanging it up during the process.

As for a workaround, I am able to select "Open in..." in Synqion, select "Save to Files", and copy it to the Strongbox folder.  This will prompt me to replace the existing database or create a new copy.  The new copy will show up in the Strongbox database list.

**Comment by mmcguill** [comment]
Thanks @shad0whawk - will take a look into this soon

**Comment by mmcguill** [comment]
This should be fixed for you with 1.28.1 @shad0whawk

**Comment by shad0whawk** [comment]
It seems to work again using 1.28.1 if the application has been opened and unlocked assuming the user has enabled the application lock settings. Still doesn’t work if the application is closed and/or locked. The unlocking action overrides the open action and the open action seems to be discarded versus waiting for the unlock to complete. 

If the application is closed or open in the background but locked, it fails. If not open in the background, I get a message stating Error Opening. If it’s open but locked, I don’t get any error message but the database doesn’t open and no error message.

**Comment by mmcguill** [comment]
I see this too... fix coming shortly.

**Comment by shad0whawk** [comment]
I see you made some changes in the latest update. The open with functionality seems to work again, but something else broke now. Strongbox no longer prompts me to update or create new if the database already exists. Can you fix it so that this works again when I copy it in?

**Comment by mmcguill** [comment]
I see the issue, thanks again @shad0whawk. Fix on the way shortly.

**Comment by mmcguill** [comment]
Hi @shad0whawk this should be fixed for you with the release of 1.29.0... let me know

**Comment by shad0whawk** [comment]
I quickly tested it and it works as expected—no other issues surfaced. Thank you!

**Comment by shad0whawk** [comment]
I hate to do this to you but this functionality seems to be broke again in v1.31.0.  I try to open it form another app, it switches to Strongbox, but then nothing happens. This is for both a database that does not exist already in Strongbox as well as one that does. I tried both my phone and iPad. Previous version installed on my other phone still works fine.

**Comment by mmcguill** [comment]
Should be patched for you now with 1.31.1 @shad0whawk - apologies, this bug just won't die

**Comment by shad0whawk** [comment]
Lol yes it’s fixed again. Thank you!
