### ISSUE TITLE
iOS UI Bugs:  Keyboard Activation and Window Positions

### ISSUE THREAD

**Issue by shad0whawk** [mmcguill/Strongbox#126]
I'm using version 1.29.1 and found a few minor issues.  

If I (1) tap "+" on the Databases tab, (2) select "New Database (Advanced)...", (3) "KeePass 2 Advanced", (4) select "Local Device", (5) select "Yes", the "Create New Database" window is displayed with a blinking cursor in the "Database Name" field, but the keyboard doesn't pop up automatically or even when I tap in the "Database Name" field.  I have to tap in the "Master Password" field for it to show, and then go back to the "Database Name" field.

Also, I tried creating a new test database and I unknowingly tried to use the same name as an existing one--ironically "Test".  The problem I encountered was that the "Create" button didn't turn blue (activate) after typing in a password.  It took me a minute to figure out that it wasn't activating because the database name was in use.  I'd suggest activating the "Create" button once the user starts typing in the password, and then display an error message upon tapping "Create" if the database name is in use.  It may save someone a bit of frustration in the future.

Also, I had the "Create New Database" window on the screen and my phone screen locked.  When I unlocked the phone, the "Create New Database" window displayed in the upper left hand corner of the screen.  I've been able to easily replicate the issue.  Replicate by (1) tap "+" on the Databases tab, (2) select "New Database (Advanced)...", (3) "KeePass 2 Advanced", (4) select "Local Device", (5) select "Yes", (6) lock the screen while the "Create New Database" window is displayed on screen.  This seems to happen with several of the windows including the "Local Device Database Caveat" window and "What would you like to do" window that displays after tapping "+" to add a new database.

This is on both an iPhone XS Max and iPad Pro running iOS 12.3.1.

![B1B4E464-65EC-4466-9CBD-62D1008D8FE2](https://user-images.githubusercontent.com/6074105/58613705-4c9d4e80-826b-11e9-825b-adf722c40d29.png)

**Comment by mmcguill** [comment]
Thanks @shad0whawk - Definitely plan on improving this soon with a new non "alert" based view controller

**Comment by shad0whawk** [comment]
All small stuff :-)

**Comment by mmcguill** [comment]
Think this should be fixed with the introduction of the new Create/Add unified view controller. Let me know.

**Comment by shad0whawk** [comment]
Yes I see that the first two points have been address nicely.  The window positions after unlock while displayed still show up incorrectly.

**Comment by mmcguill** [comment]
Could you post a screenshot of that for me? thanks!

**Comment by shad0whawk** [comment]
Here you go from version 1.30.0...

![8C641B90-66E5-4E12-99B4-EDE0FEA683D2](https://user-images.githubusercontent.com/6074105/58901689-ed05cf80-86be-11e9-94eb-32314e442a15.png)

**Comment by shad0whawk** [comment]
It's one of those minor issues that most people will never experience, but I thought I'd point it out.  It doesn't break any functionality--just looks weird.

**Comment by mmcguill** [comment]
yeah got it, thanks!

**Comment by shad0whawk** [comment]
Issues fixed. Closing this one too...
