### ISSUE TITLE
Pin unlock ui problem on small screen, e.g. iphone se

### ISSUE THREAD

**Issue by eike-fokken** [mmcguill/Strongbox#133]
Hi there, I encountered a ui bug on the iphone se (I guess other iphones with the same small display are also affected):

in portrait mode the "Done" button is almost invisible (too far to the right), see the screenshot below. It is alos hard (but possible) to press it, one has to find a very small spot, where it reacts. In landscape mode all buttons are visible but none of them reacts to pressing them.

<img width="320" alt="2019-06-06 15-03-28-1" src="https://user-images.githubusercontent.com/33839210/59034867-60007900-886c-11e9-8acb-d71ac59edbbf.png">

On another note, but totally unimportant: I liked the letters on the touchpad, it made for more easily rembered pin codes, but I adapted...

**Comment by mmcguill** [comment]
Hi @eike-fokken, this should be fixed in version 1.30.0 - Have you tried that version?

**Comment by mmcguill** [comment]
Also, maybe you're not aware but you can switch on Instant Pin Unlock so that you don't have to hit the Done button if you like

**Comment by eike-fokken** [comment]
I'm proud to say that I actually thought of updating to the latest version before filing this report! (Had the mouse already on the submit button, to be honest)

So the problem persists.

**Comment by eike-fokken** [comment]
Wait a second, my phone does stupid things, I downloaded 1.30, but it is still on 1.29.something. I'll check back when I have the newest version.

**Comment by eike-fokken** [comment]
Hm... i feel stupid now...

Yeah, it's gone, sorry to have bothered you

**Comment by mmcguill** [comment]
Oh fantastic, great to hear it! Still worth trying out instant pin unlock feature, it’s nice!

**Comment by eike-fokken** [comment]
I just turned it on, it is definitely nice!
