### ISSUE TITLE
Bug: Incorrect pin code 3 times allows access with just TouchID

### ISSUE THREAD

**Issue by milesmcclane** [mmcguill/Strongbox#42]
With both pin code and Touch ID selected, incorrect pins code error informs of the need to re enter master credentials, but actually just reverts to Touch ID with pin disabled. 
Suggest 3 fails to either Touch ID OR Pin code reverts to needing master credentials.

**Comment by shad0whawk** [comment]
Yeah I've noticed this behavior too, but if I use Face/Touch ID, then I most-likely wouldn't be using a PIN.  I view the PIN as a way to avoid retyping a long master password which is the same functionality Face/Touch ID provide.  But from a consistency and security perspective, it should request the master password and disable Face/Touch ID under the assumption that someone enabled both for a reason.

**Comment by milesmcclane** [comment]
I like the added security of a pin plus Touch ID, and I especially like the duress pin, which can only be enabled with the PIN number enabled. 
Really if any of the methods fail, however they’re enabled, it should revert to the strongest barrier possible, the master credentials.

**Comment by shad0whawk** [comment]
I agree as I sit here and think through different use cases.

**Comment by mmcguill** [comment]
This is fixed now with 1.21.1. Revert to Master Credentials if either convenience method is unavailable (and both are marked as required).

**Comment by milesmcclane** [comment]
Yes and me, the issue is not resolved. It’s they same behaviour as the original op

**Comment by mmcguill** [comment]
Good catch, I didn't think about this scenario, only if someone switches off (in preferences) Touch ID/PIN (or disabled Touch ID system wide), but not the 3 Incorrect PIN Disabling situation.

**Comment by mmcguill** [comment]
This should be fixed with 1.21.2 in the App Store now. Will leave issue open here for a while, to see if things are working as expected...
