### ISSUE TITLE
iOS: Browse UI - Bug in Edit Mode

### ISSUE THREAD

**Issue by shad0whawk** [mmcguill/Strongbox#88]
There’s a bug that appears around the “Cancel” button when editing a database that results in the “Cancel” button not reverting back the the “<“ symbol. This results in the user being unable to go back the the previous screen. To replicate the issue, open the database, swipe left on an entry to display the entry options to delete, repeat this on other entries but do it quicker, this issue will appear after doing that a few times. I was able to recreate it very easily. I made a video to highlight the error if you’d like me to send it to you.

**Comment by mmcguill** [comment]
Thanks @shad0whawk. Sure feel free to send it to me.

**Comment by shad0whawk** [comment]
I sent the video to support@strongboxsafe.com

**Comment by mmcguill** [comment]
This should be fixed now in 1.27.2

**Comment by shad0whawk** [comment]
Hmm this issue is still not fixed for me in 1.27.2 and is super easy to accidentally invoke.

**Comment by shad0whawk** [comment]
Just curious if you had any updates on the bug fix for this issue.

**Comment by shad0whawk** [comment]
I guess I asked a bit too early. Looks fixed in the latest update. Closing...

**Comment by shad0whawk** [comment]
One last follow up comment. So the issue of not being able to return to the previous screen is fixed; however, it’s weird that the “cancel” button lingers but doesn’t actually do anything when this race condition is activated.

**Comment by mmcguill** [comment]
Ok, I haven't had the time to look into this properly, but I do have plans to improve this Browse Screen coming up, so I will hopefully be able to improve things then
