### ISSUE TITLE
Mac: Clear Clipboard on Lock or Exit

### ISSUE THREAD

**Issue by mmcguill** [mmcguill/Strongbox#92]
Clipboard should be cleared if (auto clear is configured on) on Lock or Exit.

**Comment by mmcguill** [comment]
Done with 1.7.0

**Comment by jaworski** [comment]
Downloaded/Installed 1.7.0 from the App Store and gave it a shot. I'm still not seeing the clipboard being cleared when the app locks the password database.  I let the lock timeout, and I also locked it manually via cmd-L, and both times, I could still paste the passwd into a text editor.  Tried to exit and then paste into the text editor and same thing, it was still there. (Not sure how to reopen this issue, I may not have permissions.)

**Comment by mmcguill** [comment]
Should definitely work on Exit, but I forgot about the Locking situation... Reopened...

**Comment by mmcguill** [comment]
Should be fixed now in 1.7.1
